# Web server settings
server:
  host: "0.0.0.0"
  port: 8000

# List of embedding models to load and serve.
# 'name' is the alias you will use in API calls.
# 'hf_model_path' is the model identifier from Hugging Face Hub.
models:
  - name: "CLIP-ViT-B-32-laion2B-s34B-b79K"
    hf_model_path: "laion/CLIP-ViT-B-32-laion2B-s34B-b79K"
    trust_remote_code: true
    tensor_parallel_size: 1  # Adjust based on your number of GPUs
    max_model_len: 77      # Max sequence length for the model

  # - name: "gte-large"
  #   hf_model_path: "thenlper/gte-large"
  #   trust_remote_code: true
  #   tensor_parallel_size: 1
  #   max_model_len: 512

#  - name: "e5-large"
#    hf_model_path: "intfloat/e5-large-v2"
#    trust_remote_code: true
#    tensor_parallel_size: 1
#    max_model_len: 512
