# Benchmark Configuration for VectorSQL

database:
  name: 'test'
  # 重要提示: 将此路径更新为您的 .sqlite 文件
  path: 'data/vector_database.sqlite'

# sqlite-lembed 的嵌入模型配置
embedding:
  # 要在 lembed() 函数中使用的模型的注册名称
  name: 'all-MiniLM-L6-v2'
  # GGUF 模型文件的路径
  model_path: 'embed-model/all-MiniLM-L6-v2.e4ce9877.q8_0.gguf'

# SQL 文件的路径
queries:
  - name: 'gold_standard'
    path: 'queries/gold.sql'
    is_gold: true
  - name: 'test'
    path: 'queries/test_2.sql'
    is_gold: false
    
metrics:
  - execution_time
  - result_count
  - accuracy
  - name: mrr
    k: 100
  - name: map
    k: 100
  - name: ndcg
    k: 100

# 保存结果的位置
output:
  dir: 'results/'
  # `json` 或 `csv`
  format: 'json'
