# Benchmark Configuration for VectorSQL

database:
  name: 'test'
  path: 'bench/vector_database_2.sqlite'

embedding:
  name: 'all-MiniLM-L6-v2'
  model_path: 'method/model/encoder/all-MiniLM-L6-v2.e4ce9877.q8_0.gguf'


queries:
  - name: 'gold_standard'
    path: 'bench/queries/sample_gold.sql'
    is_gold: true
  - name: 'test'
    path: 'bench/queries/sample_test.sql'
    is_gold: false

metrics:
  - execution_time
  - result_count
  - accuracy
  - name: mrr
    k: 100
  - name: map
    k: 100
  - name: ndcg
    k: 100


output:
  dir: 'results/'
  format: 'json'
