# ==================================================
#         Text2VectorSQL Evaluation Framework
# ==================================================

# --- Database Configuration ---
# Base directory for database files (only for SQLite)
# For SQLite: db_identifier is a relative path to the database file
# For PostgreSQL/ClickHouse: db_identifier is the database name

#数据库的根目录
base_dir: /mnt/b_public/data/ydw/Text2VectorSQL/Data_Synthesizer/pipeline/sqlite/results/test/vector_databases

evaluation_report_file: evaluation_report.json

#项目的根目录
project_dir: /mnt/b_public/data/ydw/Text2VectorSQL/

# --- SQL Execution Configuration ---
# Path to the configuration for the ExecutionEngine
engine_config_path: Execution_Engine/engine_config.yaml

# The database backend type for this evaluation run.
# Supported types: 'sqlite', 'postgresql', 'clickhouse'
db_type: 'sqlite'

#待测评的数据的文件路径
eval_data_file: /mnt/b_public/data/ydw/Text2VectorSQL/Evaluation_Framework/input_output.json



# Output file to save the SQL execution results (intermediate file)
execution_results_file: sql_execution_results.json


# --- Embedding Service Configuration ---
# Embedding service will be automatically started by default
embedding_service:
  # Whether to automatically manage the embedding service lifecycle
  auto_manage: true
  
  # Server configuration
  host: "127.0.0.1"
  port: 8000
  
  # Model configuration
  models:
    - name: "all-MiniLM-L6-v2"
      hf_model_path: "/mnt/b_public/data/ydw/Text2VectorSQL/Embedding_Service/models_cache/all-MiniLM-L6-v2"
      trust_remote_code: true
      tensor_parallel_size: 1
      max_model_len: 256
    
    # Additional models can be configured here
    # - name: "gte-large"
    #   hf_model_path: "thenlper/gte-large"
    #   trust_remote_code: true
    #   tensor_parallel_size: 1
    #   max_model_len: 512




# --- Evaluation & Metrics Configuration ---
# Select the metrics you want to calculate.
metrics:
  # --- Set-based Metrics (order doesn't matter) ---
  - name: 'exact_match'    # 0/1 score for perfect set match
  - name: 'f1_score'       # The harmonic mean of precision and recall
  - name: 'precision'
  - name: 'recall'

  # --- Rank-aware Metrics (order matters) ---
  - name: 'map'            # Mean Average Precision
  - name: 'mrr'            # Mean Reciprocal Rank
  - name: 'ndcg'           # Normalized Discounted Cumulative Gain
    k: 10                  # The '@k' value for NDCG (e.g., ndcg@10)

llm_evaluation:
  # Enable or disable LLM-based evaluation
  enabled: false  # 设置为 true 启用 LLM 评估


  # LLM API configuration
  api_url: "http://123.129.219.111:3000/v1/chat/completions"
  api_key: "sk-GBD9BZqsXcgZXtWFVLraCy1U5Wws2Ix7xYzwTjHvBRij2MPQ"  # 替换为您的 API Key
  model_name: "gpt-4o"  # 可选: gpt-4, gpt-3.5-turbo 等
  
  # Request timeout in seconds
  timeout: 60
  
  # Optional: Whether to include LLM evaluation details in the report
  include_details: true
  # --- LLM-based Metrics (requires LLM evaluation to be enabled) ---
  # These metrics will only be calculated if llm_evaluation.enabled is true
  # - name: 'llm_sql_skeleton'      # LLM评估的SQL骨架正确性
  # - name: 'llm_vector_component'  # LLM评估的向量组件正确性
  # - name: 'llm_overall'           # LLM评估的综合得分

# The final evaluation report will be saved to this file.

